# Netlify-CMS Configuration
# See https://www.netlifycms.org/docs/configuration-options/

site_url: "https://www.themagiclab.org"
display_url: "https://www.themagiclab.org"
logo_url: "/style/magic-lab-logo.svg"

backend:
  name: github
  repo: uts-magic-lab/www.themagiclab.org
  branch: master

media_folder: "source/images" # Folder where user uploaded files should go
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "source/pages"
    create: true
    preview_path: "{{permalink}}"
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: "URL", name: "permalink", default: "{{slug}}"}
      - {label: "Layout", name: "layout", widget: hidden, default: "page"}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}

  - name: "news"
    label: "News"
    label_singular: "News Item"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: "/{{year}}/{{month}}/{{day}}/{{title}}/"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "custom-pages"
    label: "Custom Pages"
    files:
      - name: "people"
        label: "People"
        file: "source/custom_pages/people.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "URL", name: "permalink", default: "{{slug}}"}
          - {label: "Layout", name: "layout", widget: hidden, default: "page"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Sections, name: sections, widget: list,
              fields: [
                {label: "Heading", name: "heading", widget: string},
                {label: Items, name: items, widget: list,
                  fields: [
                    {label: "Name", name: "name", widget: "string"},
                    {label: "Link", name: "link", widget: "string", required: false},
                    {label: "Photo", name: "photo", widget: "image", required: false},
                    {label: "Date", name: "date", widget: "string", required: false},
                    {label: "Employer", name: "employer", widget: "string", required: false},
                    {label: "Research Topic", name: "researchtopic", widget: "string", required: false},
                    {label: "Bio", name: "bio", widget: "markdown", required: false},
                  ]
                }
              ]
            }

      - name: "research-projects"
        label: "Research Projects"
        file: "source/custom_pages/research-projects.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: "URL", name: "permalink", default: "{{slug}}"}
          - {label: "Layout", name: "layout", widget: hidden, default: "page"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Projects", name: "items", widget: "list", fields: [
              {label: "Project Title", name: "projecttitle", widget: "string"},
              {label: "Date", name: "date", widget: "string", required: false},
              {label: "Grant", name: "grant", widget: "string", required: false},
              {label: "Funding", name: "funding", widget: "string", required: false},
              {label: "Chief Investigators", name: "chiefinvestigators", widget: "string", required: false},
              {label: "Partners", name: "partners", widget: "string", required: false},
              {label: "Link", name: "link", widget: "string", required: false},
              {label: "Summary", name: "summary", widget: "markdown", required: false}
            ]}

      - name: "leadership"
        label: "Leadership"
        file: "source/custom_pages/leadership.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "URL", name: "permalink", default: "{{slug}}"}
          - {label: "Layout", name: "layout", widget: hidden, default: "page"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Sections, name: sections, widget: list,
              fields: [
                {label: "Heading", name: "heading", widget: string},
                {label: Items, name: items, widget: list,
                  fields: [
                    {label: Name, name: name, widget: string, required: false},
                    {label: Date, name: date, widget: string, required: false},
                    {label: Link, name: link, widget: string, required: false},
                    {label: Location, name: location, widget: string, required: false},
                    {label: Who, name: who, widget: string, required: false},
                    {label: Description, name: description, widget: markdown, required: false}
                  ]
                }
              ]
            }

      - name: "invited-speaker-presentations"
        label: "Leadership"
        file: "source/custom_pages/invited-speaker-presentations.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "URL", name: "permalink", default: "{{slug}}"}
          - {label: "Layout", name: "layout", widget: hidden, default: "page"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Sections, name: sections, widget: list,
              fields: [
                {label: "Heading", name: "heading", widget: string},
                {label: Items, name: items, widget: list,
                  fields: [
                    {label: Name, name: name, widget: string, required: false},
                    {label: Date, name: date, widget: string, required: false},
                    {label: Link, name: link, widget: string, required: false},
                    {label: Location, name: location, widget: string, required: false},
                    {label: Who, name: who, widget: string, required: false},
                    {label: Description, name: description, widget: markdown, required: false}
                  ]
                }
              ]
            }

  - name: "data"
    label: "Data"
    files:
      - name: "navbar"
        label: "Navbar"
        file: "source/_data/navbar.yml"
        fields:
          - {label: "Items", name: "items", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Link", name: "link", widget: "string"},
            ]}
